@WebApiMetrcNewYork.App_HostAddress = http://localhost:5100

@WebApiMetrcNewYork.App_SecureHostAddress = https://localhost:7100

@lastModifiedStart = lastModifiedStart=2025-11-07
@lastModifiedEnd = lastModifiedEnd= 2025-11-15
@pageNumber = pageNumber=1
@pageSize = pageSize=20
@packageLabel = AAAFF03000002EA000000004

GET {{WebApiMetrcNewYork.App_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{WebApiMetrcNewYork.App_SecureHostAddress}}/weatherforecast/
Accept: application/json

### Metrc New York - Sandbox query via Local API.
###
# GET Active Packages using Common Query Params.
GET {{WebApiMetrcNewYork.App_SecureHostAddress}}/api/metrcny/packages/active?{{lastModifiedStart}}&{{lastModifiedEnd}}&{{pageNumber}}&{{pageSize}}
Accept: application/json

###
# GET Active Package By Label
GET {{WebApiMetrcNewYork.App_SecureHostAddress}}/api/metrcny/packages/{{packageLabel}}
Accept: application/json

### Active Deliveries via Metrc New York - Sandbox query via Local API.
# GET Active Deliveries using Common Query Params.
GET {{WebApiMetrcNewYork.App_SecureHostAddress}}/api/metrcny/deliveries/active?{{lastModifiedStart}}&{{lastModifiedEnd}}&{{pageNumber}}&{{pageSize}}
Accept: application/json

###
# GET Delivery By Id
@id = 1
GET {{baseUrl}}/sales/v2/deliveries/{{id}}?licenseNumber={{license}}
Authorization: Basic {{basic}}
Accept: application/json

###
# POST Deliveries (one delivery)
POST {{baseUrl}}/sales/v2/deliveries?licenseNumber={{license}}
Authorization: Basic {{basic}}
Content-Type: application/json
Accept: application/json

[
  {
    "SalesDateTime": "2025-10-31T12:00:00",
    "SalesCustomerType": "Consumer",
    "ConsumerId": "ABC123",
    "Transactions": [
      {
        "PackageLabel": "NYTAG0000000000000000001",
        "UnitOfMeasure": "Each",
        "Quantity": 1,
        "TotalPrice": 42.0
      }
    ]
  }
]